apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      name: pod-1
      labels:
        app: app-1
    spec:
      containers:
        - name: pod-1
          image: jasimpm777/app-1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: app-1

    ---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: app-1
